version: '3'
services: 
    flask:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        command: flask run --host=0.0.0.0
        environment: 
            - FLASK_APP=./backend/server.py
            - FLASK_DEBUG=1
        ports: 
             - "5000:5000"
        volumes: 
            - ./:/work